"""Add description to Character

Revision ID: e9f96fee382f
Revises: 9b922e7c0738
Create Date: 2025-03-23 12:17:43.204129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9f96fee382f'
down_revision = '9b922e7c0738'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'book', ['book_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('character_relationship', schema=None) as batch_op:
        batch_op.alter_column('character1_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('character2_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('book_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_index('ix_character_relationship_book_id')
        batch_op.drop_index('ix_character_relationship_character1_id')
        batch_op.drop_index('ix_character_relationship_character2_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character_relationship', schema=None) as batch_op:
        batch_op.create_index('ix_character_relationship_character2_id', ['character2_id'], unique=False)
        batch_op.create_index('ix_character_relationship_character1_id', ['character1_id'], unique=False)
        batch_op.create_index('ix_character_relationship_book_id', ['book_id'], unique=False)
        batch_op.alter_column('book_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('character2_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('character1_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'book', ['book_id'], ['id'])
        batch_op.drop_column('description')

    # ### end Alembic commands ###
