"""empty message

Revision ID: 9b922e7c0738
Revises: 
Create Date: 2025-03-21 13:58:30.355771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b922e7c0738'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('normalized_name', sa.String(length=100), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_character_normalized_name'), ['normalized_name'], unique=False)

    op.create_table('character_relationship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character1_id', sa.Integer(), nullable=True),
    sa.Column('character2_id', sa.Integer(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['character1_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['character2_id'], ['character.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character1_id', 'character2_id', 'book_id', name='unique_relationship')
    )
    with op.batch_alter_table('character_relationship', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_character_relationship_book_id'), ['book_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_character_relationship_character1_id'), ['character1_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_character_relationship_character2_id'), ['character2_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character_relationship', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_character_relationship_character2_id'))
        batch_op.drop_index(batch_op.f('ix_character_relationship_character1_id'))
        batch_op.drop_index(batch_op.f('ix_character_relationship_book_id'))

    op.drop_table('character_relationship')
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_character_normalized_name'))

    op.drop_table('character')
    op.drop_table('book')
    # ### end Alembic commands ###
